/**
 * en_US locale strings
 */


var i18n = {
    // Common
    TITLE_SITE: 'Red Aril - DMP',
    TITLE_ANALYTICS: 'Analytics',
    TITLE_MAPPER: 'Audience Activation',
    TITLE_PIXELS: 'Tags and Pixels',
    TITLE_HELP: 'Help',
    MENU_HELP: 'Help',
    COLON: ': ',
    DOLLAR: '($)',

    BUTTON_NEXT: 'Next',
    BUTTON_OK: 'OK',
    BUTTON_CREATE: 'Create',
    BUTTON_SAVE: 'Save',
    BUTTON_SAVE_AND_CREATE_ANOTHER: 'Save And Create Another',
    BUTTON_SAVE_ACTIVATE: 'Save & Activate',
    BUTTON_CANCEL: 'Cancel',

    MESSAGE_LOADING: 'Loading...',
    MESSAGE_LOADING_DATA: 'Loading data...',
    MESSAGE_LOADING_PARAMETERS: 'Loading parameters...',
    MESSAGE_DELETING: 'Deleting...',
    MESSAGE_SENDING_DATA: 'Sending data...',
    MESSAGE_CONNECTING: 'Connecting...',
    MESSAGE_COMING_SOON: 'Coming soon...',
    MESSAGE_FORM_INVALID_VALUES: 'Invalid form values',
    MESSAGE_ALERT: 'Alert Message',
    MESSAGE_SAVED: 'Data Saved',
    MESSAGE_NO_DATA_TO_SUBMIT: 'No data to submit',
    MESSAGE_DATA_ALREADY_SENT: 'Data already sent. Wait for response',

    MESSAGE_UPDATING_DATA: 'Updating data...',
    MESSAGE_WRITING_DATA: 'Writing data...',
    MESSAGE_CREATING_RECORD: 'Creating a record...',
    MESSAGE_UPDATING_RECORD: 'Updating a record...',
    MESSAGE_DELETING_RECORD: 'Deleting a record...',
    MESSAGE_DATA_PROCESSING_ERROR: 'Data processing error',
    MESSAGE_RECALCULATING: 'Recalculating...',

    MESSAGE_ACTION_CONFIRMATION: 'Are you sure?',
    MESSAGE_DELETE_REPORT_CONFIRMATION: 'Are you sure you want to delete this report?' ,
    MESSAGE_TITLE_CONFIRM_ACTION: 'Confirm Action',

    LABEL_ALL: 'All',
    LABEL_ADD_NEW: 'Add New',
    LABEL_ACTIVATE: 'Activate',
    LABEL_ARCHIVE: 'Archive',
    LABEL_CANCEL: 'Cancel',
    LABEL_CONTINUE: 'Continue',
    LABEL_COPY: 'Copy',
    LABEL_DATE_FROM: 'Date From',
    LABEL_DATE_TO: 'Date To',
    LABEL_DATE_START: 'Start Date',
    LABEL_DATE_END: 'End Date',
    LABEL_DELETE: 'Delete',
    LABEL_DOWNLOAD: 'Download',
    LABEL_DUPLICATE: 'Duplicate',
    LABEL_EDIT: 'Edit',
    LABEL_NEW: 'New',
    LABEL_PAUSE: 'Pause',
    LABEL_REFRESH: 'Refresh',
    LABEL_VIEW_DETAILS: 'View Details',
    
    STRING_COPYRIGHT: 'Copyright &copy;  Red Aril, Inc. All Rights Reserved.',
    STRING_YES: 'Yes',
    STRING_NO: 'No',

    // Validation
    MESSAGE_ALPHANUMSPACES_VALIDATION: 'Not a valid name. Only alphanumeric and spaces chars allowed.',
    MESSAGE_NAME_VALIDATION: 'The value must begin and end with a non-space character. Tha value must be more than two letters long.',

    // Error
    TITLE_ERROR: 'Error Occurred',
    LABEL_AJAX_ERROR: 'Ajax error',
    LABEL_URL: 'URL',
    LABEL_METHOD: 'Method',
    LABEL_RESPONSE: 'Response',
    MESSAGE_ERROR: 'We are experiencing trouble processing your request. <br/> If the problem persists, please refresh the page and try again.',
    MESSAGE_REQUEST_ERROR: 'Request error',
    MESSAGE_UNKNOWN_ACTION: 'Unknown action "{0}"',

    ERROR_ADVERTISER_NAME_EXISTS: 'An Advertiser with this name already exists.',
    ERROR_ADVERTISER_CAMPAIGN_NAME_EXISTS: 'An Advertiser Campaign with this name already exists.',
    ERROR_VALUE_EXISTS: 'Record with this value already exists.',
    ERROR_NAME_EXISTS: 'Record with this name already exists.',
    ERROR_WRONG_CAMP_ID: 'Wrong Campaign ID ',
    ERROR_CAMP_GRID_IS_NOT_FOUND: 'Campaigns store is not found.',
    ERROR_CAMP_IS_EMPTY: 'Campaign ID is defined, but Campaign Object is empty.',
    ERROR_CAMP_NAME_EXISTS: 'You already have a data campaign with this name. Please rename this data campaign.',
    ERROR_AUDIENCE_GROUP_IS_EMPTY: 'Please select an Audience Group.',
    ERROR_ADVERTISER_IS_EMPTY: 'Please select an Advertiser.',
    ERROR_ADVERTISER_CAMPAIGN_IS_EMPTY: 'Please select an Advertiser Campaign.',
    ERROR_AUDIENCE_SEGMENT_DATA: 'Wrong Audience Segment Data.',
    ERROR_AUDIENCE_SEGMENT_SUBSECTIONS: 'No subSections found.',
    ERROR_WRONG_FACTORY_CALL: ' Unknown data source type. Allowed only types: FIRST_PARTY, SECOND_PARTY, THIRD_PARTY_BLUEKAI, THIRD_PARTY_STANDARD, RED_ARIL_MODELED',
    ERROR_CHECKGROUP: 'At least one checkbox must be checked',

    // Login
    TITLE_LOGIN: 'Login',
    MENU_LOGOUT: 'Logout',
    LABEL_LOGIN: 'Sign In',
    LABEL_LOGOUT: 'Logout',
    LABEL_USERNAME: 'Username',
    LABEL_PASSWORD: 'Password',
    LABEL_REMEMEBER: 'Remember Me',
    MESSAGE_LOGIN_FAILED: 'Login Failed.',
    MESSAGE_ACCESS_GRANTED: 'Access granted.',
    MESSAGE_ENTER_USERNAME: 'Enter your username.',
    MESSAGE_ENTER_PASSWORD: 'Enter password.',
    MESSAGE_LOGOUT_FAILED: 'Log out failed.',
    MESSAGE_FAILED_USER_INFO: 'Failed to load user info.',

    // Templates
    TITLE_TEMPLATES: 'Report Templates',
    TITLE_CHOOSE_TEMPLATE: '1. Select Template',
    TITLE_TEMPLATE_SETTINGS: '2. Complete Form',
    TITLE_TEMPLATE_DIMENSIONS: 'Dimensions',
    TITLE_TEMPLATE_METRICS: 'Metrics',
    TITLE_CREATE_REPORT_FAILED: 'Create report failed!',
    MENU_TEMPLATES: 'Report Templates',
    HEADER_TEMPLATE_NAME: 'Template Name',
    HEADER_TEMPLATE_DESCRIPTION: 'Description',
    HEADER_TEMPLATE_DIMENSIONS: 'Dimensions',
    HEADER_TEMPLATE_METRICS: 'Metrics',
    HEADER_TEMPLATE_CONSTRAINTS: 'Constraints',
    HEADER_TEMPLATE: 'Template',
    HEADER_REPORT_NAME: 'Report Name',
    LABEL_TEMPLATES: 'Report Templates',
    LABEL_AUDIENCE_GROUP: 'Audience Group',
    LABEL_AUDIENCE_GROUPS: 'Audience Group(s)',
    LABEL_AUDIENCE_SEGMENT: 'Audience Segment',
    LABEL_AUDIENCE_SEGMENTS: 'Audience Segment(s)',
    LABEL_CREATE_REPORT: 'Create Report',
    LABEL_TEMPLATE_DIMENSIONS: 'Dimensions',
    LABEL_TEMPLATE_METRICS: 'Metrics',
    ITEM_FULL_AUDIENCE_GROUPS: 'All Groups',
    ITEM_FULL_AUDIENCE_SEGMENTS: 'All Segments',
    MESSAGE_AUDIENCE_GROUP_NOT_LOADED: 'Audience group(s) could not be loaded.',
    MESSAGE_AUDIENCE_SEGMENTS_NOT_LOADED: 'Audience segment(s) could not be loaded.',
    MESSAGE_AUDIENCE_GROUPS_SELECT: 'Select groups.',
    MESSAGE_TEMPLATES_NOT_LOADED: 'Templates list load failed.',
    MESSAGE_TEMPLATE_LOAD_ERROR: 'Template load error.',
    MESSAGE_TEMPLATE_NOT_CHOOSEN: 'Please select a report template.',
    MESSAGE_TEMPLATE_NOT_DEFINED: 'Template is not selected from the list.',

    //Campaigns
    CAMP_NO_RESTRICTIONS: 'No Restrictions',
    CAMP_BUDGET: 'Budget ($)' ,
    CAMP_STAMPS: 'Stamps',
    CAMP_DAY: 'Day',
    CAMP_DAYS: 'Day(s)',
    CAMP_DAYS_ALL: 'All Days',
    CAMP_LIFETIME: 'Campaign Lifetime',

    MENU_CAMPAIGN: 'Data Campaign',
    MENU_CAMPAIGNS: 'Data Campaigns',
    MENU_SEGMENTS: 'Audience Segments',

    LABEL_CAMPAIGN: 'Data Campaign',
    LABEL_DATA_SOURCE:   'Data Source',
    LABEL_DATA_SOURCES: 'Data Sources',
    LABEL_DATA_SECTIONS: 'Sections',
    LABEL_PLAN_BUDGET: 'Plan Budget ($)',
    LABEL_TOTAL_BUDGET: 'Total Budget ($)',
    LABEL_REMAINING_BUDGET: 'Remaining Budget ($)',
    LABEL_PRICE: 'Price',
    LABEL_PACING: 'Pacing',
    LABEL_GOAL: 'Goal',
    LABEL_PER: 'per',
    LABEL_RECENCY: 'Recency',
    LABEL_STATUS: 'Status',
    LABEL_TARGETING: 'Targeting',
    LABEL_ADD_ADVERTISER: 'Add Advertiser',
    LABEL_ADVERTISER: 'Advertiser',
    LABEL_ADVERTISER_NAME: 'Advertiser Name',
    LABEL_ADD_ADVERTISER_CAMPAIGN: 'Add Campaign',
    LABEL_ADVERTISER_CAMPAIGN: 'Advertiser Campaign Name',
    LABEL_ADVERTISER_CAMPAIGN_NAME: 'Advertiser Campaign',
    LABEL_DATA_CAMPAIGN_NAME: 'Data Campaign Name',
    LABEL_CAMPAIGN_NAME: 'Campaign Name',

    MESSAGE_SELECT_CAMPAIGN: "Select a campaign...",
    MESSAGE_SELECT_ADVERTISER: "Select an advertiser...",
    MESSAGE_SELECT_AUDIENCE_SEGMENT: "Select an audience segment...",
    MESSAGE_CAMPAIGNS_LIST_EMPTY : 'You have no data campaigns.',
    MESSAGE_CAMPAIGNS_SETTINGS_LIST_EMPTY: 'Settings list could not be loaded.',
    MESSAGE_ENTER_ADVERTISER_NAME: 'Enter Advertiser Name.',
    MESSAGE_ENTER_ADVERTISER_CAMPAIGN_NAME: 'Enter Advertiser Campaign Name.',

    TITLE_CREATE_ADVERTISER: 'Create New Advertiser',
    TITLE_CREATE_ADVERTISER_CAMPAIGN: 'Create New Advertiser Campaign',
    TITLE_CREATE_CAMP: 'Create Data Campaign',
    TITLE_EDIT_CAMP: 'Edit Data Campaign',
    TITLE_VIEW_CAMP: 'Data Campaign Details',
    TITLE_COPY_CAMP: 'Copy Data Campaign',


    TITLE_EDIT_ACTIVE_CAMPAIGN: 'Edit an active Data Campaign',
    QUESTION_EDIT_ACTIVE_CAMPAIGN:
            'Please note that in order to edit a data campaign, it must first be paused.<br/>' +
                    'Pressing <b>&laquo;Continue&raquo;</b> will pause this data campaign so you can make your chanages.<br/>' +
                    'If you do not wish to pause it, please press <b>&laquo;Cancel&raquo;</b>',
    TITLE_PAUSE_CAMPAIGN: 'Pause a Data Campaign',
    QUESTION_PAUSE_CAMPAIGN: 'Pausing a data campaign will stop the passing of your data segments for ad serving.<BR/> Are you sure you would like to pause this data campaign?',
    TITLE_ARCHIVE_CAMPAIGN: 'Archive a Data Campaign',
    QUESTION_ARCHIVE_CAMPAIGN:
            'Please note that once you archive a Data Campaign, <b>you will not be able to activate</b> it in the future.<br/>' +
                    'Are you sure you want to archive this Data Campaign?',
    TITLE_ACTIVATE_CAMPAIGN: 'Activate a Data Campaign',
    QUESTION_ACTIVATE_CAMPAIGN: 'Activating a data campaign will incur data costs for any 3rd party data.<BR/> Are you sure you would like to activate this data campaign?',

    // Audience Segments
    TITLE_SEGMENTS: 'Audience Segments',
    HEADER_AUDIENCE_SEGMENTS_GROUPS: 'Audience Segments',
    HEADER_SIZE_SEGMENTS: 'Size',
    HEADER_SEGMENT_STATUS: 'Status',
    MENU_CREATE_SEGMENT: 'Create Segment',
    MENU_ADD_DATA_SOURCE_SEGMENTS: 'Add Data Source',
    MENU_EDIT_SEGMENT: 'Edit Segment',
    MENU_DELETE_SEGMENT: 'Delete Segment',
    MENU_SHOW_USAGE_SEGMENT: 'Show Use',
    MENU_ADD_SECTION_SEGMENTS: 'Add Section',
    MENU_DELETE_DATA_SOURCE_SEGMENTS: 'Delete Data Source',
    MENU_EDIT_SECTION_SEGMENTS: 'Edit Section',
    MENU_DELETE_SECTION_SEGMENTS: 'Delete Section',
    TITLE_EDIT_SEGMENT: 'Edit Segment',
    TITLE_CREATE_SEGMENT: 'Create Segment',
    TITLE_COPY_SEGMENT: 'Copy Segment',
    LABEL_SEGMENT_NAME: 'Segment Name',
    MESSAGE_SEGMENT_NAME_EMPTY: 'Enter Segment Name.',
    TITLE_ADD_DATA_SOURCE_SEGMENTS: 'Add Section: Select Data Source',
    TITLE_ADD_SECTION_SEGMENTS: 'Add Section',
    LABEL_NEWLY_CREATED_SECTION_SEGMENTS: 'Section',
    HEADER_AUDIENCE_CATEGORY_SEGMENTS: 'Audience Category',
    HEADER_FLOOR_PRICE_SEGMENTS: 'Floor Price',
    HEADER_RECOMMENDED_PRICE_SEGMENTS: 'Recom. Price',
    HEADER_DATA_TYPE_SEGMENTS: 'Data Type',
    TITLE_DATA_TYPE_SEGMENTS: 'Data Type',
    TITLE_AUDIENCE_CATEGORY_SEGMENTS: 'Audience Category',
    TITLE_SECTION_SEGMENTS: 'Section. Size:',
    TITLE_EDIT_SECTION_SEGMENTS: 'Edit Section',
    LABEL_ADD_SUB_SECTION_SEGMENTS: 'Add Subsection',
    LABEL_ADD_SUB_SECTION_SEGMENTS_EXCLUSIONS: 'Add Exclusions',
    HEADER_CATEGORIES_NAME_SEGMENTS: 'Name',
    HEADER_CATEGORIES_SIZE_SEGMENTS: 'Size',
    LABEL_SUBSECTION_SEGMENTS: 'Subsection: Any (OR) categories',
    LABEL_AND_SUBSECTIONS_SEGMENTS: 'AND',
    //LABEL_ADD_SEGMENT: 'New Audience Segment',
    LABEL_ADD_SEGMENT: 'New',
    LABEL_PUBLISH_SEGMENT: 'Publish',
    LABEL_UNPUBLISH_SEGMENT: 'Unpublish',
    LABEL_COPY_SEGMENT: 'Copy',
    LABEL_ARCHIVE_SEGMENT: 'Archive',
    HEADER_PRICE_SEGMENTS: 'Price',
    MESSAGE_TITLE_CANNOT_ADD_CATEGORY: 'Cannot add category.',
    MESSAGE_CANNOT_ADD_CATEGORY_SAME_ERROR: 'This category has already been added to this subsection.',
    MESSAGE_CANNOT_ADD_CATEGORY_PARENT_ERROR: 'This category cannot be added because one of its parents has already been added to this subsection.',
    MESSAGE_TITLE_CANNOT_PUBLISH_SEGMENT: 'Cannot publish segment',
    MESSAGE_CANNOT_PUBLISH_SEGMENT: 'The audience segment you are trying to publish is incomplete. It must contain at least one audience category in at least one section from at least one data source.',
    MESSAGE_ARCHIVE_SEGMENT: 'Please note that in order to archive an audience segment you must first set its status to unpublished. Setting an audience segment to unpublished will make it unavailable (e.g. in data campaign, analytics, etc.). Are you sure you want to continue?',
    MESSAGE_WRONG_SEGMENT_XML: 'Server returned wrong XML for selected audienceSegment.',
    TITLE_CAMPAIGNS_LIST_FORM_SEGMENTS: ' ',
    HEADER_DATA_CAMPAIGN_NAME_SEGMENTS: 'Data Campaign',
    HEADER_DATA_CAMPAIGN_STATUS_SEGMENTS: 'Status',
    MESSAGE_SELECT_DATA_SOURCE_SEGMENTS: 'Please, Select a Data Source.',
    MESSAGE_ERROR_ADD_BLUE_KAI_TO_NON_EMPTY_SEGMENT: 'Blue Kai data cannot share an Audience Segment with other Data Sources.',
    MESSAGE_ERROR_ADD_SAME_DATA_SOURCE: 'One segment cannot have two sections with the same data source.',
    LABEL_SUBSECTION_IN_TREE_SEGMENTS: 'Subsection',
    TITLE_ERROR_ADD_SOURCE: 'Cannot use this data source',
    MESSAGE_TITLE_EMPTY_DATA_TYPES: 'No Data Types found.',
    MESSAGE_EMPTY_DATA_TYPES: 'This Data Source has no Data Types.',
    MESSAGE_DELETE_CONFIRMATION_SEGMENT: 'Are you sure you want to delete this segment?',
    MESSAGE_DELETE_CONFIRMATION_SECTION: 'Are you sure you want to delete this section?',
    MESSAGE_ARCHIVE_CONFIRMATION_SEGMENT: 'Are you sure you want to archive this segment?',
    MESSAGE_SEGMENT_NAME_ALREADY_TAKEN_TITLE: 'Cannot save segment.',
    MESSAGE_SEGMENT_NAME_ALREADY_TAKEN: 'This name is already taken.',
    MESSAGE_PUBLISH_CONFIRMATION_SEGMENT: 'Are you sure you want to publish this segment?',    
    MESSAGE_UNPUBLISH_CONFIRMATION_SEGMENT: 'Are you sure you want to unpublish this segment?',
    MESSAGE_NO_SEGMENT_ID_FOUND: 'No segment id found in URL',
    MESSAGE_NO_SECTION_ID_FOUND: 'No section id found in URL',
    MESSAGE_NO_DATASOURCE_ID_FOUND: 'No datasource id found in URL',

    // Reports
    TITLE_REPORTS: 'Audience Reports',
    TITLE_REPORT: 'Report "{0}" ({1}-{2})',
    MENU_REPORTS: 'Audience Reports',
    HEADER_LAST_STATUS_UPDATED: 'Last Status Updated',
    HEADER_REPORT: 'Report',
    HEADER_REPORT_STATUS: 'Report Status',
    LABEL_REPORTS: 'Audience Reports',
    LABEL_REPORT_NAME: 'Report Name',
    LABEL_REPORT_DATE_FROM: 'From',
    LABEL_REPORT_DATE_TO: 'To',
    LABEL_REPORT_AUDIENCE_GROUPS: 'Audience Group(s)',
    LABEL_REPORT_AUDIENCE_SEGMENTS: 'Audience Segment(s)',
    LABEL_SUMMARY_GROUP_ITEM: 'Item',
    LABEL_SUMMARY_GROUP_ITEMS: 'Items',
    LABEL_SUMMARY_ITEMS: 'Items',
    LABEL_SUMMARY_MAX: 'Max',
    LABEL_SUMMARY_MIN: 'Min',
    LABEL_SUMMARY_AMOUNT: 'Amount',
    LABEL_SUMMARY_AVERAGE: 'Average',
    LABEL_SUMMARY_FIRST: 'First',
    LABEL_SUMMARY_LAST: 'Last',
    MESSAGE_REPORT_TOO_BIG_TITLE: 'This report has too many rows to display.',
    MESSAGE_REPORT_TOO_BIG: 'This report contains too many rows to be displayed. Please download it instead.',
    MESSAGE_REPORT_NO_VIEW: 'Report is not available for viewing.',
    MESSAGE_REPORTS_LIST_EMPTY: 'You have no saved reports.',
    MESSAGE_REPORT_NOT_COMPLETED: 'Report is not completed.',
    MESSAGE_REPORT_NOT_DELETED: 'Report could not be deleted.',
    MESSAGE_BAD_REPORT_DATA: 'Bad report data.',
    MESSAGE_REPORT_DATA_EMPTY: 'This report has no data.',
    MESSAGE_NO_REPORT_DATA_ID_FOUND: 'URL should have type, report and run parameters.',

    // Flex Reports
    TITLE_JUST_REPORT: 'Report',
    TITLE_JUST_REPORTS: 'Reports',
    TITLE_AUDIENCE_CATEGORIES: 'Audience Category',
    TITLE_CROSS_CATEGORIES: 'Cross Category',
    TITLE_AUDIENCE_SEGMENTS: 'Audience Segment',
    TITLE_SEGMENT_FORECAST: 'Segment Forecast',
    TITLE_DATA_USAGE: 'Data Usage',
    TITLE_FLEXIBLE_REPORTS: 'Analytics Reports',
    TITLE_AUDIENCE_CATEGORIES_FLEX_REPORTS: 'Audience Category Reports',
    TITLE_CROSS_CATEGORIES_FLEX_REPORTS: 'Cross Category Reports',
    TITLE_AUDIENCE_SEGMENTS_FLEX_REPORTS: 'Audience Segment Reports',
    TITLE_SEGMENT_FORECAST_FLEX_REPORTS: 'Segment Forecast Reports',
    TITLE_DATA_USAGE_FLEX_REPORTS: 'Data Usage Reports',
    TITLE_AUDIENCE_CATEGORIES_FLEX_REPORT: 'Audience Category Report',
    TITLE_CROSS_CATEGORIES_FLEX_REPORT: 'Cross Category Report',
    TITLE_AUDIENCE_SEGMENTS_FLEX_REPORT: 'Audience Segment Report',
    TITLE_SEGMENT_FORECAST_FLEX_REPORT: 'Segment Forecast Report',
    TITLE_DATA_USAGE_FLEX_REPORT: 'Data Usage Report',
    TITLE_DOWNLOAD_REPORT: 'Download Report',
    TITLE_DELETE_REPORT: 'Delete Report',
    TITLE_REPORT_DETAILS: 'Report details',
    TITLE_REPEATING_REPORT: 'Recurring Reports',
    TITLE_CREATE_NEW_FLEXIBLE_REPORT: 'Create new Analytics Report',
    TITLE_EDIT_FLEXIBLE_REPORT: 'Edit Analytics Report',
    TITLE_CONSTRAINTS: 'Constraints',
    TITLE_DIMENSIONS: 'Dimensions',
    TITLE_METRICS: 'Metrics',
    TITLE_TIME_SETTINGS: 'Time Settings',
    TITLE_VIEW_UNIT_TIME: 'View (unit of time)',
    TITLE_AGGREGATION: 'Aggregation',
    TITLE_SAVE_SCHEDULE_EMAIL: 'Save, Schedule and Email',

    LABEL_NEW_REPORT: 'New report',
    LABEL_VIEW_REPORT: 'View Report',
    LABEL_VIEW_REPORTS: 'View Reports',
    LABEL_CREATE: 'Create',
    LABEL_DATA_RANGE: 'Date Range',
    LABEL_RUN_THIS_REPORT: 'Run This Report',
    LABEL_EMAIL_REPORT_TO: 'Email Report To',

    TEXT_SELECT_TIME_PERIOD: 'select time period...',
    TEXT_ATTACHED_AS: 'attached as',
    TEXT_SEPARATE_RECIPIENTS: 'Separate recipients with commas or leave blank for no email.',

    HEADER_DATE: 'Date',

    TOOLTIP_REQUEST_NEW_REPORT: 'Request a new report',

    MESSAGE_LOADING_FLEX_REPORTS: 'Loading Flex Reports...',
    MESSAGE_FLEX_REPORTS_LIST_EMPTY: 'Analytics Reports list is empty',
    MESSAGE_SELECT_REPORT: 'Please select a report',
    MESSAGE_REPORT_NOT_READY: 'Report is in progress',
    MESSAGE_NO_DATA_IN_REPORT: 'There is no data in the report'
}
